-   id: import-linter
    name: import-linter
    description: Import Linter allows you to define and enforce rules for the internal and external imports within your Python project.
    entry: lint-imports
    language: system
    types: [python]
    pass_filenames: false
